DELETE FROM tbl_centres;
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (1, 'Belfast, The Royal Belfast Hospital FOR Sick Children', 'Belfast', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (2, 'Birmingham Children\'s Hospital', 'Birmingham', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (3, 'Bristol Royal Hospital FOR Children', 'Bristol', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (4, 'Cardiff,  Children\'s Hospital for Wales', 'Cardiff', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (5, 'Glasgow - Yorkhill, Royal Hospital FOR Sick Children', 'Glasgow', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (6, 'Leeds -  St James University Hospital, Dept of Paediatric Nephrology', 'Leeds', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (7, 'Liverpool - Royal Liverpool Children\'s Hospital, Alder Hey', 'Liverpool AH', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (8, 'London -  Evelina Children\'s Hospital', 'London Evelina', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (9, 'London -  Great Ormond Street Hospital FOR Children NHS Trust', 'London GOS', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (10, 'Manchester -  Royal Manchester\'s Children\'s Hospital', 'Manchester', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (11, 'Newcastle - Royal Victoria Infirmary, Paediatric Unit', 'Newcastle', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (12, 'Nottingham - QMC - Children\'s Kidney Unit', 'Nottingham', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (13, 'Southampton General Hospital', 'Southampton', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (14, 'Renal Registry', 'Renal Registry', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (15, 'Demonstration Entries', 'Demonstration', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (16, 'UNKNOWN', 'UNKNOWN', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (55, 'Christian Medical College, Vellore, India', 'Vellore', 2);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (56, 'St John\'s Medical College Hospital, Bangalore, India', 'Bangalore', 2);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (57, 'ALL India Institute of Medical Science, NEW Dehli, India', 'NEW Dehli', 2);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (58, 'Children Medical Centre Hospital, Tehran', 'Tehran', 2);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (99, 'Demonstration Entries', 'Demonstration2', 2);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (59, 'Aberdeen Royal Infirmary', '', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (60, 'Monklands Hospital (Airdrie)', 'Airdrie', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (61, 'Antrim Hospital', 'Antrim', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (62, 'Ysbyty Gwynedd (Bangor)', 'Bangor', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (63, 'Basildon Hospital', 'Basildon', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (64, 'Belfast City Hospital', 'Belfast', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (65, 'Ulster Hospital (Belfast)', 'Belfast', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (66, 'Heartlands Hospital (B\'Ham)', 'Birmingham', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (67, 'Queen Elizabeth Hospital (B\'Ham)', 'Birmingham', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (68, 'St Lukes Hospital (Bradford)', 'Bradford', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (69, 'Royal Sussex County Hospital', 'Brighton', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (70, 'Southmead Hospital (Bristol)', 'Bristol', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (71, 'Addenbrookes Hospital (Cambridge', 'Cambridge', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (72, 'Kent & Canterbury Hospital', 'Canterbury', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (73, 'University Hospital of Wales (Cardiff)', 'Cardiff', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (74, 'Cumberland Infirmary', 'Carlisle', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (75, 'St Helier Hospital (Carshalton)', 'Carshalton', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (76, 'Broomfield Hospital (Chelmsford)', 'Chelmsford', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (77, 'Colchester General Hospital', 'Colchester', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (78, 'Walsgrave Hospital (Coventry)', 'Coventry', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (79, 'Royal Derby Hospital', 'Derby', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (80, 'Doncaster Royal Infirmary', 'Doncaster', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (81, 'Dorset County Hospital', 'Dorchester', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (82, 'Russells Hall Hospital (Dudley)', 'Dudley', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (83, 'Dumfries & Galloway Royal Infirmary', 'Dumfries', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (84, 'Ninewells Hospital (Dundee)', 'Dundee', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (85, 'Queen Margaret\'s Hospital (Dunf\'line)', 'Dunfermline', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (86, 'Royal Infirmary of Edinburgh (NEW Royal)', 'Edinburgh', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (87, 'Royal Devon AND Exeter Hospital (Wonford)', 'Exeter', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (88, 'Glasgow Royal Infirmary & Western Infirmary', 'Glasgow', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (89, 'Gloucester Royal Hospital', 'Gloucester', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (90, 'Hull Royal Infirmary', 'Hull', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (91, 'Raigmore Hospital (Inverness)', 'Inverness', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (92, 'Ipswich Hospital', 'Ipswich', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (93, 'Crosshouse Hospital (Kilmarnock)', 'Kilmarnock', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (94, 'St James\'s University Hospital (Leeds)', 'Leeds', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (95, 'Leicester General Hospital', 'Leicester', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (96, 'Royal Liverpool Childrens Hospital', 'Liverpool', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (97, 'Royal Liverpool University Hospital', 'Liverpool', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (98, 'University Hospital Aintree', 'Liverpool', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (136, 'Guy\'s and St Thomas\'s Hospital', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (100, 'Guy\'s Hospital - Paediatric', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (101, 'King\'s College Hospital', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (102, 'Barts AND the London Hospital', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (103, 'Great Ormond Street Hospital FOR Children', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (104, 'West London', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (105, 'Royal Free & Middlesex Hospital', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (106, 'St George\'s Hospital', 'London', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (107, 'Altnagelvin Hospital (Derry)', 'Londonderry', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (108, 'Manchester Royal Infirmary', 'Manchester', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (109, 'James Cook University Hospital (Middlesbro)', 'Middlesbrough', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (110, 'Freeman Hospital & Royal Victoria Infirmary(Newc)', 'Newcastle-upon-Tyne', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (111, 'Daisy Hill Hospital (Newry)', 'Newry', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (112, 'Norfolk & Norwich University Hospital', 'Norwich', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (113, 'Nottingham City Hospital', 'Nottingham', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (114, 'Tyrone County Hospital', 'Omagh', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (115, 'Oxford Radcliffe Hospital', 'Oxford', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (116, 'Derriford Hospital (Plymouth)', 'Plymouth', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (117, 'Queen Alexandra Hospital (P\'smouth)', 'Portsmouth', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (118, 'Royal Preston Hospital', 'Preston', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (119, 'Royal Berkshire Hospital (Reading)', 'Reading', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (120, 'Ysbyty Glan Clwyd (Rhyl)', 'Rhyl', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (121, 'Hope Hospital (Salford)', 'Salford', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (122, 'Northern General Hospital (Sheff\'d)', 'Sheffield', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (123, 'Gilbert Bain Hospital (Shetland)', 'Shetland', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (124, 'Royal Shrewsbury Hospital', 'Shrewsbury', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (125, 'Southampton General Hospital - Paediatric', 'Southampton', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (126, 'Southend Hospital', 'Southend-ON-Sea', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (127, 'Lister Hospital', 'Stevenage', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (128, 'University Hospital of North Staffordshire (Stoke)', 'Stoke-ON-Trent', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (129, 'Sunderland Royal Hospital', 'Sunderland', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (130, 'Morriston Hospital (Swansea)', 'Swansea', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (131, 'Royal Cornwall Hospital (Treliske-Truro)', 'Truro', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (132, 'Arrowe Park Hospital (Wirral)', 'Wirral', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (133, 'NEW CROSS Hospital (Wolverh\'ton)', 'Wolverhampton', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (134, 'Wrexham Maelor Hospital', 'Wrexham', 1);
INSERT INTO tbl_centres(cID, cName, cAbbrev, cCountry) VALUES (135, 'York District General Hospital', 'York', 1);


